#!/usr/bin/env node
/*
 * build.js
 * --------------------------------------------------------------------------
 * Reads site.config.json and transforms it into site.content.js.
 *
 * site.content.js is an ES module that exports the file system data in the
 * exact shape the <tui-file-manager> component expects, plus the site meta.
 * The component's own styling is never touched by this build.
 *
 * Usage
 *   node build.js            # build once
 *   node build.js --watch    # rebuild whenever site.config.json changes
 *
 * The config controls only the tree structure and the content. The visual
 * style of the component is fixed in tui-file-manager.js.
 */

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const { imageToAscii } = require('./tools/image-to-ascii.js');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'site.config.json');
const OUT = path.join(ROOT, 'site.content.js');
const HOME_IMG = path.join(ROOT, 'assets', 'home-ascii.jpg');
const SMILE_IMG = path.join(ROOT, 'assets', 'home-smile.jpg');
const HOME_OUT = path.join(ROOT, 'site.home.js');

function readConfig() {
  const raw = fs.readFileSync(SRC, 'utf8');
  try {
    return JSON.parse(raw);
  } catch (e) {
    throw new Error(SRC + ' is not valid JSON: ' + e.message);
  }
}

/** Sanitize the label used in error messages. */
function label(name) {
  return name && name.trim() ? name : '?';
}

function transformChildren(parentName, arr) {
  if (!Array.isArray(arr)) {
    throw new Error(`"${label(parentName)}".children must be an array`);
  }
  const seen = new Set();
  const out = [];
  for (const raw of arr) {
    if (!raw || typeof raw.name !== 'string' || !raw.name.trim()) {
      throw new Error(`Every node under "${label(parentName)}" needs a non-empty "name"`);
    }
    if (seen.has(raw.name)) {
      throw new Error(`Duplicate node name "${raw.name}" under "${label(parentName)}"`);
    }
    seen.add(raw.name);
    out.push(transformNode(raw, parentName));
  }
  return out;
}

function transformNode(raw, parentName) {
  const type = raw.type || (Array.isArray(raw.children) ? 'dir' : 'file');

  if (type === 'dir') {
    return {
      name: raw.name,
      type: 'dir',
      modified: raw.modified || '',
      children: transformChildren(raw.name, raw.children || []),
    };
  }

  const content = raw.content || '';
  const size = raw.size != null ? raw.size : Buffer.byteLength(content, 'utf8');

  const node = {
    name: raw.name,
    type: 'file',
    size,
    modified: raw.modified || '',
  };

  for (const key of ['title', 'date', 'href', 'summary']) {
    if (raw[key] != null && raw[key] !== '') node[key] = raw[key];
  }
  if (Array.isArray(raw.tags) && raw.tags.length) node.tags = raw.tags;
  if (content) node.content = content;

  if (raw.size == null && size === 0 && !content) {
    console.warn(`  warn: "${raw.name}" has no size and no content`);
  }

  return node;
}

function countNodes(node) {
  let dirs = 0;
  let files = 0;
  const walk = (n) => {
    if (n.type === 'dir') {
      dirs += 1;
      (n.children || []).forEach(walk);
    } else {
      files += 1;
    }
  };
  walk(node);
  return { dirs, files };
}

async function buildHomeAssets() {
  const banner =
    '/* AUTO-GENERATED by build.js from assets/home-ascii.jpg and assets/home-smile.jpg. Do not edit by hand. */';

  let ascii = { cols: 0, rows: 0, art: '' };
  if (fs.existsSync(HOME_IMG)) {
    try {
      ascii = await imageToAscii(HOME_IMG, { cols: 60 });
      console.log('home ascii: ' + ascii.cols + 'x' + ascii.rows + ' grid');
    } catch (e) {
      console.warn('home ascii: ' + e.message + ' -> empty');
    }
  } else {
    console.log('home ascii: no ' + path.basename(HOME_IMG) + ' -> empty');
  }

  let smile = { cols: 0, rows: 0, art: '' };
  if (fs.existsSync(SMILE_IMG)) {
    try {
      smile = await imageToAscii(SMILE_IMG, { cols: 12 });
      console.log('home smile: ' + smile.cols + 'x' + smile.rows + ' grid');
    } catch (e) {
      console.warn('home smile: ' + e.message + ' -> empty');
    }
  } else {
    console.log('home smile: no ' + path.basename(SMILE_IMG) + ' -> empty');
  }

  const output =
    banner +
    '\n\nexport const homeAscii = ' + JSON.stringify(ascii, null, 2) + ';\n\n' +
    'export const homeSmile = ' + JSON.stringify(smile, null, 2) + ';\n';
  fs.writeFileSync(HOME_OUT, output);
  console.log('built ' + path.basename(HOME_OUT));
}

function build() {
  const cfg = readConfig();
  const meta = cfg.meta || {};
  const rootName = meta.root || '~';

  const fileSystem = {
    name: rootName,
    type: 'dir',
    children: transformChildren(rootName, cfg.tree || []),
  };

  const count = countNodes(fileSystem);
  const banner =
    '/* AUTO-GENERATED by build.js from site.config.json. Do not edit by hand. */';
  const output =
    banner +
    '\n\nexport const siteMeta = ' + JSON.stringify(meta, null, 2) + ';\n\n' +
    'export const fileSystem = ' + JSON.stringify(fileSystem, null, 2) + ';\n';

  fs.writeFileSync(OUT, output);
  console.log('built ' + path.basename(OUT));
  console.log('  root=' + rootName + '  dirs=' + count.dirs + '  files=' + count.files);
}

function watch() {
  const rebuild = () => {
    console.log('\n[watch] change detected, rebuilding...');
    try {
      build();
      buildHomeAssets().catch((e) => console.error('[watch] ' + e.message));
    } catch (e) {
      console.error('[watch] ' + e.message);
    }
  };
  fs.watchFile(SRC, { interval: 300 }, rebuild);
  fs.watchFile(HOME_IMG, { interval: 300 }, rebuild);
  fs.watchFile(SMILE_IMG, { interval: 300 }, rebuild);
  console.log('watching ' + path.basename(SRC) + ', ' + path.basename(HOME_IMG) + ' and ' + path.basename(SMILE_IMG) + '  (Ctrl+C to stop)');
}

const watchMode = process.argv.includes('--watch');

async function main() {
  try {
    build();
    await buildHomeAssets();
  } catch (e) {
    console.error('build failed: ' + e.message);
    process.exit(1);
  }
  if (watchMode) watch();
}

main();
