#!/usr/bin/env node
/*
 * build.js
 * --------------------------------------------------------------------------
 * Reads site.config.json and transforms it into site.content.js.
 *
 * site.content.js is an ES module that exports the file system data in the
 * exact shape the <tui-file-manager> component expects, plus the site meta.
 * The component's own styling is never touched by this build.
 *
 * Usage
 *   node build.js            # build once
 *   node build.js --watch    # rebuild whenever site.config.json changes
 *
 * The config controls only the tree structure and the content. The visual
 * style of the component is fixed in tui-file-manager.js.
 */

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const { imageToAscii } = require('./tools/image-to-ascii.js');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'site.config.json');
const OUT = path.join(ROOT, 'site.content.js');
const CONTENT_DIR = path.join(ROOT, 'content');
const HOME_IMG = path.join(ROOT, 'assets', 'home-ascii.jpg');
const SMILE_IMG = path.join(ROOT, 'assets', 'home-smile.jpg');
const HOME_OUT = path.join(ROOT, 'site.home.js');

function readConfig() {
  const raw = fs.readFileSync(SRC, 'utf8');
  try {
    return JSON.parse(raw);
  } catch (e) {
    throw new Error(SRC + ' is not valid JSON: ' + e.message);
  }
}

/** Sanitize the label used in error messages. */
const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

/** Format a Date like "Aug 31 13:44" for display in the file manager. */
function formatModified(d) {
  const mm = MONTHS[d.getMonth()];
  const dd = String(d.getDate()).padStart(2, '0');
  const hh = String(d.getHours()).padStart(2, '0');
  const mi = String(d.getMinutes()).padStart(2, '0');
  return `${mm} ${dd} ${hh}:${mi}`;
}

/** Parse the YAML-ish front-matter block at the top of a markdown file. */
function parseFrontmatter(text) {
  if (text.slice(0, 3) !== '---') return { meta: {}, body: text };
  const m = /\n---\s*\n/.exec(text);
  if (!m) return { meta: {}, body: text };
  const fmText = text.slice(3, m.index);
  const body = text.slice(m.index + m[0].length);
  const meta = {};
  for (const line of fmText.split('\n')) {
    const kv = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!kv) continue;
    const key = kv[1];
    let val = kv[2].trim();
    if (/^\[.*\]$/.test(val)) {
      val = val.slice(1, -1).split(',').map((s) => s.trim().replace(/^['"]|['"]$/g, '')).filter(Boolean);
    } else {
      val = val.replace(/^['"]|['"]$/g, '');
    }
    meta[key] = val;
  }
  return { meta, body };
}

/** Latest mtime as a display string for a directory. */
function dirModified(absDir) {
  let max = 0;
  for (const ent of fs.readdirSync(absDir, { withFileTypes: true })) {
    const abs = path.join(absDir, ent.name);
    if (ent.isDirectory()) {
      const sub = dirModified(abs);
      if (sub > max) max = sub;
    } else if (/\.md$/i.test(ent.name)) {
      const st = fs.statSync(abs);
      if (st.mtimeMs > max) max = st.mtimeMs;
    }
  }
  return max ? formatModified(new Date(max)) : '';
}

/** Scan a content directory and return the file-system tree for the UI. */
function scanContentDir(absDir, relDir) {
  const children = [];
  const entries = fs.readdirSync(absDir, { withFileTypes: true });
  entries.sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true }));
  for (const ent of entries) {
    const abs = path.join(absDir, ent.name);
    const rel = relDir ? relDir + '/' + ent.name : ent.name;
    if (ent.isDirectory()) {
      children.push({
        name: ent.name,
        type: 'dir',
        modified: dirModified(abs),
        children: scanContentDir(abs, rel),
      });
    } else if (/\.md$/i.test(ent.name)) {
      const raw = fs.readFileSync(abs, 'utf8');
      const { meta } = parseFrontmatter(raw);
      const node = {
        name: ent.name,
        type: 'file',
        size: fs.statSync(abs).size,
        modified: meta.modified || '',
        path: 'content/' + rel,
      };
      for (const key of ['title', 'date', 'href', 'summary']) {
        if (meta[key]) node[key] = meta[key];
      }
      if (Array.isArray(meta.tags) && meta.tags.length) node.tags = meta.tags;
      children.push(node);
    }
  }
  return children;
}

function countNodes(node) {
  let dirs = 0;
  let files = 0;
  const walk = (n) => {
    if (n.type === 'dir') {
      dirs += 1;
      (n.children || []).forEach(walk);
    } else {
      files += 1;
    }
  };
  walk(node);
  return { dirs, files };
}

async function buildHomeAssets() {
  const banner =
    '/* AUTO-GENERATED by build.js from assets/home-ascii.jpg and assets/home-smile.jpg. Do not edit by hand. */';

  let ascii = { cols: 0, rows: 0, art: '' };
  if (fs.existsSync(HOME_IMG)) {
    try {
      ascii = await imageToAscii(HOME_IMG, { cols: 60 });
      console.log('home ascii: ' + ascii.cols + 'x' + ascii.rows + ' grid');
    } catch (e) {
      console.warn('home ascii: ' + e.message + ' -> empty');
    }
  } else {
    console.log('home ascii: no ' + path.basename(HOME_IMG) + ' -> empty');
  }

  let smile = { cols: 0, rows: 0, art: '' };
  if (fs.existsSync(SMILE_IMG)) {
    try {
      smile = await imageToAscii(SMILE_IMG, { cols: 12 });
      console.log('home smile: ' + smile.cols + 'x' + smile.rows + ' grid');
    } catch (e) {
      console.warn('home smile: ' + e.message + ' -> empty');
    }
  } else {
    console.log('home smile: no ' + path.basename(SMILE_IMG) + ' -> empty');
  }

  const output =
    banner +
    '\n\nexport const homeAscii = ' + JSON.stringify(ascii, null, 2) + ';\n\n' +
    'export const homeSmile = ' + JSON.stringify(smile, null, 2) + ';\n';
  fs.writeFileSync(HOME_OUT, output);
  console.log('built ' + path.basename(HOME_OUT));
}

function build() {
  const cfg = readConfig();
  const meta = cfg.meta || {};
  const rootName = meta.root || '~';

  const fileSystem = {
    name: rootName,
    type: 'dir',
    modified: '',
    children: fs.existsSync(CONTENT_DIR) ? scanContentDir(CONTENT_DIR, '') : [],
  };

  const count = countNodes(fileSystem);
  const banner =
    '/* AUTO-GENERATED by build.js from the content/ directory. Do not edit by hand. */';
  const output =
    banner +
    '\n\nexport const siteMeta = ' + JSON.stringify(meta, null, 2) + ';\n\n' +
    'export const fileSystem = ' + JSON.stringify(fileSystem, null, 2) + ';\n';

  fs.writeFileSync(OUT, output);
  console.log('built ' + path.basename(OUT));
  console.log('  root=' + rootName + '  dirs=' + count.dirs + '  files=' + count.files);
}

function watch() {
  const rebuild = () => {
    console.log('\n[watch] change detected, rebuilding...');
    try {
      build();
      buildHomeAssets().catch((e) => console.error('[watch] ' + e.message));
    } catch (e) {
      console.error('[watch] ' + e.message);
    }
  };
  fs.watchFile(SRC, { interval: 300 }, rebuild);
  fs.watchFile(HOME_IMG, { interval: 300 }, rebuild);
  fs.watchFile(SMILE_IMG, { interval: 300 }, rebuild);
  if (fs.existsSync(CONTENT_DIR)) {
    try {
      fs.watch(CONTENT_DIR, { recursive: true }, rebuild);
    } catch (e) {
      fs.watchFile(CONTENT_DIR, { interval: 300 }, rebuild);
    }
  }
  console.log('watching ' + path.basename(SRC) + ', ' + path.basename(CONTENT_DIR) + ', ' + path.basename(HOME_IMG) + ' and ' + path.basename(SMILE_IMG) + '  (Ctrl+C to stop)');
}

const watchMode = process.argv.includes('--watch');

async function main() {
  try {
    build();
    await buildHomeAssets();
  } catch (e) {
    console.error('build failed: ' + e.message);
    process.exit(1);
  }
  if (watchMode) watch();
}

main();
