/* AUTO-GENERATED by build.js from site.config.json. Do not edit by hand. */

export const siteMeta = {
  "title": "TUI-FS",
  "description": "A self-hosted blog rendered as a TUI file manager.",
  "root": "~"
};

export const fileSystem = {
  "name": "~",
  "type": "dir",
  "children": [
    {
      "name": "Posts",
      "type": "dir",
      "modified": "Aug 31 13:44",
      "children": [
        {
          "name": "hello-world.md",
          "type": "file",
          "size": 406,
          "modified": "Aug 31 13:40",
          "title": "Hello World",
          "date": "Aug 31 2026",
          "tags": [
            "intro",
            "meta"
          ],
          "content": "# Hello World\n\nWelcome to my self-hosted blog.\n\nThis site is a static page. The file list you see is a JSON configuration file. To add a new article, edit `site.config.json` and run `node build.js` again.\n\n## What you can do\n\n- Add a file node under any directory\n- Set a `title`, a `date` and a list of `tags`\n- Write the body in Markdown\n- Link a `href` to open an external page instead of inline content"
        },
        {
          "name": "dracula-theme.md",
          "type": "file",
          "size": 215,
          "modified": "Aug 30 18:05",
          "title": "Why I Chose Dracula",
          "date": "Aug 30 2026",
          "tags": [
            "design",
            "color"
          ],
          "content": "# Why I Chose Dracula\n\nThe Dracula palette is dark, warm and readable for long sessions.\n\n- Background `#282A36`\n- Foreground `#F8F8F2`\n- Accent `#BD93F9`\n\nEvery color used by this component comes from `DRACULA.md`."
        },
        {
          "name": "tui-in-the-browser.md",
          "type": "file",
          "size": 239,
          "modified": "Aug 28 22:12",
          "title": "TUI in the Browser",
          "date": "Aug 28 2026",
          "tags": [
            "frontend"
          ],
          "content": "# TUI in the Browser\n\nA TUI style does not need a terminal. The look comes from a monospace font, right-angle borders and box-drawing characters.\n\nThe directory tree uses `├─`, `└─` and `│`. Panels always keep `border-radius: 0`."
        }
      ]
    },
    {
      "name": "Pinned",
      "type": "dir",
      "modified": "Aug 27 20:40",
      "children": [
        {
          "name": "about.md",
          "type": "file",
          "size": 117,
          "modified": "Aug 27 20:40",
          "title": "About",
          "date": "Aug 27 2026",
          "tags": [
            "meta"
          ],
          "content": "# About\n\nI write about code, design and the tools I build.\n\nThis blog is a static site built from a single JSON file."
        }
      ]
    },
    {
      "name": "Links",
      "type": "dir",
      "modified": "Aug 25 09:00",
      "children": [
        {
          "name": "dracula.md",
          "type": "file",
          "size": 123,
          "modified": "",
          "title": "Dracula Theme",
          "date": "Aug 25 09:00",
          "href": "https://draculatheme.com",
          "summary": "The color scheme used by this site.",
          "content": "Opening an external link.\n\nClicking this entry opens https://draculatheme.com in a new tab, because it has an `href` value."
        }
      ]
    },
    {
      "name": "Archive",
      "type": "dir",
      "modified": "Aug 01 03:00",
      "children": [
        {
          "name": "reading-list.md",
          "type": "file",
          "size": 79,
          "modified": "Aug 01 03:00",
          "title": "Reading List",
          "date": "Aug 01 2026",
          "tags": [
            "notes"
          ],
          "content": "# Reading List\n\n- The Design of Everyday Things\n- Dracula Theme\n- Atomic Habits"
        }
      ]
    }
  ]
};
