/* AUTO-GENERATED by build.js from the content/ directory. Do not edit by hand. */

export const siteMeta = {
  "title": "TUI BLOG",
  "description": "A personal blog with a TUI style.",
  "root": "~"
};

export const fileSystem = {
  "name": "~",
  "type": "dir",
  "modified": "",
  "children": [
    {
      "name": "计算机图形学",
      "type": "dir",
      "modified": "Sep 13 10:24",
      "children": [
        {
          "name": "SSR反射中出现多余命中的原因及解决方法.md",
          "type": "file",
          "size": 5710,
          "modified": "Sep 13 12:00",
          "path": "content/计算机图形学/SSR反射中出现多余命中的原因及解决方法.md",
          "title": "SSR反射中出现多余命中的原因及解决方法",
          "date": "Sep 13 2026",
          "summary": "从单点深度比较到方案B的「两端采样 + 连续性校验」，记录屏幕空间反射命中检测的三次渐进式改进",
          "tags": [
            "unity",
            "urp",
            "ssr",
            "shader"
          ]
        }
      ]
    },
    {
      "name": "人工智能",
      "type": "dir",
      "modified": "",
      "children": []
    },
    {
      "name": "随笔",
      "type": "dir",
      "modified": "",
      "children": []
    },
    {
      "name": "About",
      "type": "dir",
      "modified": "Sep 05 22:58",
      "children": [
        {
          "name": "ascii-art.md",
          "type": "file",
          "size": 740,
          "modified": "Sep 05 12:00",
          "path": "content/About/ascii-art.md",
          "title": "ASCII Art",
          "date": "Sep 05 2026",
          "summary": "A short introduction to ASCII art.",
          "tags": [
            "ascii"
          ]
        },
        {
          "name": "dracula-theme.md",
          "type": "file",
          "size": 797,
          "modified": "Sep 05 12:00",
          "path": "content/About/dracula-theme.md",
          "title": "The Dracula Theme",
          "date": "Sep 05 2026",
          "summary": "A short introduction to the Dracula color scheme.",
          "tags": [
            "theme"
          ]
        }
      ]
    },
    {
      "name": "DCC工具链",
      "type": "dir",
      "modified": "",
      "children": [
        {
          "name": "Blender",
          "type": "dir",
          "modified": "",
          "children": []
        },
        {
          "name": "Procreate",
          "type": "dir",
          "modified": "Sep 06 00:57",
          "children": [
            {
              "name": "如何解决电容笔抖动.md",
              "type": "file",
              "size": 1281,
              "modified": "Sep 05 12:00",
              "path": "content/DCC工具链/Procreate/如何解决电容笔抖动.md",
              "title": "如何解决电容笔抖动",
              "date": "Sep 05 2026",
              "summary": "使用procreate内置设置解决电容笔抖动",
              "tags": [
                "procreate"
              ]
            }
          ]
        }
      ]
    }
  ]
};
